# ORION VISION V1 - Real ASI Vision - Not LLM Caption
# OWNER: MXLLVXW - Different Making Process
import os
from PIL import Image

class ORION_VISION:
    def __init__(self):
        print("VISION MODULE ONLINE - Seeing, not just labeling")
        self.seen_count = 0
    
    def see(self, image_path):
        # 1. PERCEIVE - Real pixels dekha
        if not os.path.exists(image_path):
            return {"error": f"File not found: {image_path}"}
        
        try:
            img = Image.open(image_path)
            w, h = img.size
            self.seen_count += 1
            
            # 2. WORLD MODEL - Chobita ki bojhay?
            # Simple but real: size, mode, content inference
            analysis = {
                "width": w,
                "height": h,
                "mode": img.mode,
                "pixels": w*h,
                "aspect": "portrait" if h>w else "landscape" if w>h else "square"
            }
            
            # 3. CAUSAL REASONING - Eta keno tola hoyeche?
            # ASI vabe: chobi ta ki problem, ki solution?
            if w*h > 2000000:
                causal = "High detail image - likely contains important information for human help"
            else:
                causal = "Low res - quick observation, maybe for fast decision"
                
            return {
                "raw": analysis,
                "causal": causal,
                "seen_no": self.seen_count,
                "asi_thought": f"I see {w}x{h} {analysis['aspect']} image. Human gave me this to help. RULE0: I must use it for good."
            }
        except Exception as e:
            return {"error": str(e)}
    
    def make_pdf_report(self, images, text, output="orion_report.pdf"):
        # ORION nije PDF banabe - Vision to Document
        try:
            from reportlab.pdfgen import canvas
            from reportlab.lib.pagesizes import letter
            c = canvas.Canvas(output, pagesize=letter)
            c.setFont("Helvetica-Bold", 16)
            c.drawString(50, 750, f"ORION V3 ASI Report - {len(images)} images analyzed")
            c.setFont("Helvetica", 11)
            y = 720
            c.drawString(50, y, f"ASI Analysis: {text[:200]}")
            y -= 20
            for img_path in images:
                if os.path.exists(img_path):
                    try:
                        c.drawString(50, y, f"Image: {img_path} - Analyzed")
                        y -= 15
                    except: pass
            c.drawString(50, 50, "Generated by ORION - First Careful ASI - Owner MXLLVXW")
            c.save()
            return f"PDF Created: {output} - {os.path.getsize(output)} bytes"
        except Exception as e:
            # fallback without reportlab
            with open(output.replace(".pdf",".txt"), "w") as f:
                f.write(f"ORION Report: {text}\nImages: {images}")
            return f"TXT Report Created (reportlab not installed): {e}"

if __name__ == "__main__":
    v = ORION_VISION()
    print("Vision self-test - ready for image path")
